### ISSUE TITLE
[issue] FCM ios build

### ISSUE THREAD

**Issue by hwangyena** [depromeet/pingpong-app#12]
## 이슈 내용
![image](https://user-images.githubusercontent.com/70925962/208458126-bab302e4-9a03-4613-b61f-adc11eb882e9.png)
- ios device 연결 build시 위와 같은 에러로 FCM 알림을 확인할 수 없습니다. 며칠 째 같은 빌드 에러 확인중인데, 혹시 시간 괜찮으시면 한번씩 확인 부탁드려요

## Screenshot

- 스크린샷이 있다면 첨부해주세요.

**Comment by junhaesung** [comment]
안녕하세요
RN 은 잘 모르지만 저도 flutter 에서 code signing 때문에 많이 헤매는중이어서 조심스레 코멘트 추가해봅니다

혹시 provisioning profile 은 어떻게 관리하시나요? 
xCode 에서 자동으로 관리해주거나, 수동으로 파일 import 하는 두 가지 방법이 있는걸로 알고있는데요. 
no identity found 라고 나오는걸 보니 앱의 identifier 가 provisioning profile 에 지정된 값이랑 같은지 확인해보고싶어서요.

**Comment by hwangyena** [comment]
> 

안녕하세요
기존 xCode에서 provisioning profile 관리 중이였고, identifier와 같은것 확인했습니다.
빌드시에 어떤 에러였는지 정확하게 알 수 없으나, 현재는 빌드에러를 해결한 상태입니다. (해결방안은 다른 답글로 정리하겠습니다)
코멘트 남겨주셔서 감사합니다

**Comment by hwangyena** [comment]
이슈 해결 방안
1. Pod 파일 추가 및 install
```
  pod 'Firebase/Messaging'  
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
```
2. build 파일 전체 삭제 및 rebuild
3. apple developer Certification 등 관련 key 삭제 후 다시 로드
4. FCM SDK 재설정
5. APN 인증키 재설정
6. APN 인증서 삭제

위와 같은 과정으로 앱 빌드시 에러 현상은 제거했습니다. 
다만, FCM내에서 알림을 발송할 때 기기는 추적되나 알람 전송시 messaging() 이 전송되지 않는 이슈가 있어 해결중입니다..

**Comment by junhaesung** [comment]
해결방안 공유해주셔서 감사합니다! 

---

#10 에 링크해주신 블로그 내용 참고해보니 `APN 인증 키` 방식을 쓰고있어서 저랑 다르긴한데요. 
저는 `APN 인증 키` 는 사용하지 않고 `개발, 프로덕션 APN 인증서`를 각각 등록하는 방식으로 진행했습니다. 
인증서 등록하지 않았을 때, 저도 같은 현상 겪었어서 공유드려요. (에러 로그같은건 없어보이는데 기기에서 알림 수신을 못하는 현상)

![image](https://user-images.githubusercontent.com/4813025/208665109-4ca0e63f-c97b-4ba0-b5ed-5a9ed205e153.png)
